### ISSUE TITLE
Bug with certain ip

### ISSUE THREAD

**Issue by 2403905** [oschwald/geoip2-golang#22]
Hi,
I'm running the example with ip  95.173.163.146
```
	db, err := geoip2.Open("/geo/GeoLite2-City.mmdb")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()
	// If you are using strings that may be invalid, check that ip is not nil
	ip := net.ParseIP("95.173.163.146")
	record, err := db.City(ip)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Portuguese (BR) city name: %v\n", record.City.Names["pt-BR"])
	fmt.Printf("English subdivision name: %v\n", record.Subdivisions[0].Names["en"])
	fmt.Printf("Russian country name: %v\n", record.Country.Names["ru"])
	fmt.Printf("ISO country code: %v\n", record.Country.IsoCode)
	fmt.Printf("Time zone: %v\n", record.Location.TimeZone)
	fmt.Printf("Coordinates: %v, %v\n", record.Location.Latitude, record.Location.Longitude)
```

Db I'm getting from [http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz](url)
I have error:
```
Portuguese (BR) city name: 
2016/11/25 21:11:28 http: panic serving 127.0.0.1:49426: runtime error: index out of range
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc42007e380)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x6796c0, 0xc42000c150)
	/usr/local/go/src/runtime/panic.go:458 +0x243
main.setGeo(0xc4200c00f0, 0xc420045b40, 0x0)
	/home/dodger/projects/go/src/redirector/geo_sevice.go:75 +0x5df
main.sayHello(0x7e2dc0, 0xc4200ea000, 0xc4200c00f0)
	/home/dodger/projects/go/src/redirector/redirector.go:82 +0x234
net/http.HandlerFunc.ServeHTTP(0x6e9ad8, 0x7e2dc0, 0xc4200ea000, 0xc4200c00f0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0x7fdd60, 0x7e2dc0, 0xc4200ea000, 0xc4200c00f0)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc42007e300, 0x7e2dc0, 0xc4200ea000, 0xc4200c00f0)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc42007e380, 0x7e3300, 0xc420012680)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d

```

len(record.City.Names["pt-BR"] or len(record.City.Names["en"] retturn 0 
There are no errors with other IP addresses.
I would appreciate your help.

**Comment by oschwald** [comment]
Your code has:

```
	fmt.Printf("English subdivision name: %v\n", record.Subdivisions[0].Names["en"])
```

However, in GeoLite2, there are no subdivisions for that IP address so the indexing on the slice `record.Subdivisions` fails.

**Comment by 2403905** [comment]
Thank you. :)
